export const SEED_SOURCES = [
  ["Reuters World", "https://www.reutersagency.com/feed/?best-topics=world&post_type=best"],
  ["AP Top News", "https://feeds.apnews.com/apf-topnews"],
  ["BBC World", "http://feeds.bbci.co.uk/news/world/rss.xml"],
  ["NYTimes World", "https://rss.nytimes.com/services/xml/rss/nyt/World.xml"],
  ["The Verge", "https://www.theverge.com/rss/index.xml"],
  ["TechCrunch", "https://techcrunch.com/feed/"],
  ["Ars Technica", "http://feeds.arstechnica.com/arstechnica/index"],
  ["Wired", "https://www.wired.com/feed/rss"],
  ["Bloomberg", "https://feeds.bloomberg.com/markets/news.rss"],
  ["CNBC", "https://www.cnbc.com/id/100003114/device/rss/rss.html"],
  ["Financial Times", "https://www.ft.com/rss/home"],
  ["Politico", "https://www.politico.com/rss/politicopicks.xml"],
  ["Axios", "https://api.axios.com/feed/"],
  ["NPR", "https://feeds.npr.org/1001/rss.xml"],
  ["The Guardian", "https://www.theguardian.com/world/rss"],
  ["Al Jazeera", "https://www.aljazeera.com/xml/rss/all.xml"],
  ["MIT Tech Review", "https://www.technologyreview.com/feed/"],
  ["Science Daily", "https://www.sciencedaily.com/rss/all.xml"],
  ["Nature", "https://www.nature.com/nature.rss"],
  ["CoinDesk", "https://www.coindesk.com/arc/outboundfeeds/rss/"],
] as const;
